### ISSUE TITLE
Difference: config pyproject.toml/dagster_cloud.yaml

### ISSUE THREAD

**Issue by dbrtly** [dagster-io/dagster-cloud#25]
Under what circumstances are these two config intended to be different for a dagster project deployed to dagster cloud? I don't understand why   
dagster_cloud.yaml is necessary.

I'm willing to contribute here. 

# pyproject.toml

```
[tool.dagster]
module_name = "quickstart_etl.definitions"
code_location_name = "quickstart_etl"
```

# dagster_cloud.yaml
```
locations:
  - location_name: my_location_name # the name of the code location
    code_source:
      package_name: hackernews # the name of the python package associated with the code location
```
